Fixes issue #17 (bug fixes & enhancements)
hhuOS/hhuOS pull request #18
Opened 2020-12-02 06:08 UTC by NamitS27

- Fixed `cd` and `date`(pretty print flag) command.
- Added new shell commands,
  - `ps` 
  - `mathexpr`
  - `rmdir`
  - `pwd`

2020-12-03 08:25 UTC, fruhland commented
Thank you for your submission. We will review your code over the next few days and give you feedback, if anything needs to be updated.

2020-12-07 15:02 UTC, fruhland requested changes
Please remove all build artifacts from your Pull Request (e.g. `.d`, `.bin` files and the `intird`).

2020-12-07 15:08 UTC, fruhland reviewed
Please do not remove license headers and be sure to add them to all your new files. Feel free to add yourself as authors if you edited the regarding file, but do not remove the license header.

2020-12-07 15:11 UTC, fruhland requested changes
Please do not remove license headers (e.g. `DiskInfo`) and be sure to add them to all your new files. Feel free to add yourself as authors if you edited the regarding file, but do not remove the license header.

2020-12-07 15:13 UTC, fruhland requested changes
Removed...

2020-12-07 15:17 UTC, fruhland requested changes
Scheduler: Please do not expose `readyQueues` as a public variable. If you need to access it, implement a getter-method.

2020-12-07 15:20 UTC, fruhland requested changes
As far as we know, executing `cd` without arguments on a Unix-based system, does not do anything. That is why, we implemented the command this way. We think, this is a more natural behaviour than changing to the root directory.

2020-12-07 15:35 UTC, fruhland requested changes

2020-12-07 15:35 UTC, fruhland commented on src/application/shell/command/DiskInfo.cpp
> -
Please do not remove license headers and be sure to add them to all your new files. Feel free to add yourself as authors if you edited the regarding file, but do not remove the license header.

2020-12-07 15:35 UTC, fruhland commented on src/application/shell/command/DiskInfo.h
> - */
Please do not remove license headers and be sure to add them to all your new files. Feel free to add yourself as authors if you edited the regarding file, but do not remove the license header.

2020-12-07 15:35 UTC, fruhland commented on src/application/shell/command/Ps.cpp
> +    for (const auto &queue : Kernel::Scheduler::getInstance().readyQueues) {
Please do not expose readyQueues as a public variable. If you need to access it, implement a getter-method.

2020-12-07 15:35 UTC, fruhland commented on src/device/input/Keyboard.cpp
> +        0, 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', 129, '+', '\n',
Please do not change the keyboard layout. Feel free to implement multiple layouts and a switching mechanism (this is a planned feature, anyways).

2020-12-07 15:35 UTC, fruhland commented on src/kernel/thread/Scheduler.h
> -    Util::Array<Util::ArrayBlockingQueue<Thread *>> readyQueues;
Please do not expose readyQueues as a public variable. If you need to access it, implement a getter-method.

2020-12-07 15:35 UTC, fruhland commented on src/application/shell/command/Cd.cpp
> +        shell.setCurrentWorkingDirectory(Directory::open("/"));
As far as we know, executing cd without arguments on a Unix-based system, does not do anything. That is why, we implemented the command this way. We think, this is a more natural behaviour than changing to the root directory.

2020-12-07 15:35 UTC, fruhland commented on src/lib/util/ArgumentParser.cpp
> +    for(auto it:unnamedArguments) command += it + " ";
We think that single line loops are not very readable and would prefer use of brackets and blocks.

2020-12-13 06:26 UTC, NamitS27 commented
@fruhland, the changes suggested by you has been done. Can you please verify it & suggest any further changes if required.

2020-12-15 15:51 UTC, fruhland reviewed
Thanks for your update. Everything looks good now, however we found a small bug in "mathexpr": If you execute it without any arguments, the OS crashes. Can please have a look into that, before we merge your PR?

Best regards!

2020-12-15 15:51 UTC, fruhland commented on src/application/shell/command/Mathexpr.cpp
> +        stderr << args[0] << ": Invalid command" << endl;
Could you please give a more detailed error message (e.g. "Invalid number of arguments")?

2020-12-15 15:51 UTC, fruhland commented on src/application/shell/command/Mathexpr.cpp
> +    /* Check whether more than one unamed arguments are given by the user and display the appropriate message it they do */
Please also check for zero arguments. Right now, the OS crashes when you execute "mathexpr" without any arguments.

2020-12-15 16:10 UTC, NamitS27 commented
@fruhland I have fixed the mathexpr command for zero arguments and also edited the error message by making it more precise.

2020-12-15 17:35 UTC, fruhland commented
Thanks! Everything is fine now :)

2020-12-15 17:36 UTC, merged